spring.datasource.url=jdbc:postgresql://dpg-d83fq1gg4nts73dcd0q0-a.frankfurt-postgres.render.com/schulwiki
spring.datasource.username=admin
spring.datasource.password=KM2SeGe11iJ90QdbO2snpaVH515tzJHN
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=9f3c2b7a6d1e4f8c0a9b7d2e5f1c3a8e6b9d4f7a2c1e8b5d0f9a3c6e1b7d4f8a
jwt.expiration=900000
jwt.refreshExpiration=2678400000

cors.allowed-origins=http://localhost:5173,http://localhost:8081

app.admin.username=system_administrator
app.admin.password=admin123_
app.admin.email=admin@schulwiki.com
app.admin.first-name=System
app.admin.last-name=Administrator

app.rate-limit.strict-limit=10
app.rate-limit.default-limit=120
app.rate-limit.strict-paths=/api/auth/login,/api/auth/register,/api/auth/refresh,/api/auth/valid-credentials
